# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s1554371/Processor/Processor.cache/wt [current_project]
set_property parent.project_path /home/s1554371/Processor/Processor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s1554371/Processor/Processor.srcs/sources_1/new/ALU.v
  /home/s1554371/Processor/Processor.srcs/sources_1/new/Timer.v
  /home/s1554371/Processor/Processor.srcs/sources_1/new/ROM.v
  /home/s1554371/Processor/Processor.srcs/sources_1/new/RAM.v
  /home/s1554371/Processor/Processor.srcs/sources_1/new/Processor.v
  /home/s1554371/Processor/Processor.srcs/sources_1/new/top.v
  /home/s1554371/Timing_the_world_in_decimal/Timing_the_world_in_decimal.srcs/sources_1/new/Generic_counter.v
  /home/s1554371/Processor/Processor.srcs/sources_1/new/IR_driver.v
  /home/s1554371/IR_interface_1_car/IR_interface_1_car.srcs/sources_1/new/IRTransmitterSM.v
  /home/s1554371/IR_interface_1_car/IR_interface_1_car.srcs/sources_1/new/CarParameterSelector.v
  /home/s1554371/IR_interface_1_car/IR_interface_1_car.srcs/sources_1/new/SevenSegmentDisplay.v
}
read_xdc /home/s1554371/Processor/Processor.srcs/constrs_1/new/proc_constraints.xdc
set_property used_in_implementation false [get_files /home/s1554371/Processor/Processor.srcs/constrs_1/new/proc_constraints.xdc]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
