set_property PACKAGE_PIN G2 [get_ports IR_LED]
    set_property IOSTANDARD LVCMOS33 [get_ports IR_LED]

set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]
    
set_property PACKAGE_PIN U18 [get_ports RESET]
    set_property IOSTANDARD LVCMOS33 [get_ports RESET]
    
set_property PACKAGE_PIN E19 [get_ports {CAR_SELECT_OUT[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CAR_SELECT_OUT[0]}]
set_property PACKAGE_PIN U19 [get_ports {CAR_SELECT_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CAR_SELECT_OUT[1]}]
     
set_property PACKAGE_PIN V16 [get_ports {CAR_SELECT_IN[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CAR_SELECT_IN[0]}]
set_property PACKAGE_PIN W16 [get_ports {CAR_SELECT_IN[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CAR_SELECT_IN[1]}]
    
set_property PACKAGE_PIN W7 [get_ports {SEGMENT_DISPLAY_OUT[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_OUT[6]}]
set_property PACKAGE_PIN W6 [get_ports {SEGMENT_DISPLAY_OUT[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_OUT[5]}]
set_property PACKAGE_PIN U8 [get_ports {SEGMENT_DISPLAY_OUT[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_OUT[4]}]
set_property PACKAGE_PIN V8 [get_ports {SEGMENT_DISPLAY_OUT[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_OUT[3]}]
set_property PACKAGE_PIN U5 [get_ports {SEGMENT_DISPLAY_OUT[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_OUT[2]}]
set_property PACKAGE_PIN V5 [get_ports {SEGMENT_DISPLAY_OUT[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_OUT[1]}]
set_property PACKAGE_PIN U7 [get_ports {SEGMENT_DISPLAY_OUT[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_OUT[0]}]
set_property PACKAGE_PIN U2 [get_ports {SEGMENT_DISPLAY_ANODE_ACTIVE[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_ANODE_ACTIVE[0]}]
set_property PACKAGE_PIN U4 [get_ports {SEGMENT_DISPLAY_ANODE_ACTIVE[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_ANODE_ACTIVE[1]}]
set_property PACKAGE_PIN V4 [get_ports {SEGMENT_DISPLAY_ANODE_ACTIVE[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_ANODE_ACTIVE[2]}]
set_property PACKAGE_PIN W4 [get_ports {SEGMENT_DISPLAY_ANODE_ACTIVE[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_DISPLAY_ANODE_ACTIVE[3]}]